### PR TITLE
Disambiguate parenthesized range expressions from call expressions

### PR DESCRIPTION
**Pull request by resolritter**
closes https://github.com/tree-sitter/tree-sitter-rust/issues/86

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
Thanks @resolritter. Great work, and sorry for the delay.

**Comment by aryx** [comment]
Can this PR be responsible for https://github.com/tree-sitter/tree-sitter-rust/issues/121?

**Comment by aryx** [comment]
Can this PR be responsible for the parsing error in https://github.com/tree-sitter/tree-sitter-rust/issues/107 ?

**Comment by resolritter** [comment]
@aryx see https://github.com/tree-sitter/tree-sitter-rust/pull/127

**Pull request merged**
