### PR TITLE
Parse interpolation and formatting in strings

### PR DESCRIPTION
**Pull request by mucinoab**
I based my approach in the [python implementation](https://github.com/tree-sitter/tree-sitter-python/pull/33). 
This is my fist time working with the tree-sitter machinery, please let me know of any issues.

 
Solves #129

### CODE REVIEW

**Comment by mucinoab** [comment]
Hey @maxbrunsfeld I would really appreciate if you could review this. Thanks you.

**Comment by amaanq** [comment]
The difference with Rust & Python is that in Python, an f string's interpolations are always valid, whereas in Rust it's only valid in certain macro invocations, a regular string with brackets is not an interpolation, so I don't think this makes much sense and is better left to an lsp

**Comment by mucinoab** [comment]
This is kind of a new feature for Rust. [Announcing Rust 1.58.0: Captured identifiers in format strings](https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html#captured-identifiers-in-format-strings)

And there is still a lot of work going on to improve things. 

- [Tracking issue for improving std::fmt::Arguments and format_args!()](https://github.com/rust-lang/rust/issues/99012)

**Comment by amaanq** [comment]
My point still stands, it's not valid in all string contexts and rust-analyzer handles this anyways

**Comment by ValouBambou** [comment]
Sure, maybe it needs to be only in macro context, but the feature exists for other editors like intellij and vscode since at least one year if I remember correctly, so it shouldn't be so hard to implement.

**Comment by amaanq** [comment]
The feature exists in Rust's LSP

**Comment by ValouBambou** [comment]
From what I just tested on both helix and neovim, renaming a variable doesn't rename the one inside the println string, so I'm not sure of that. Furthermore, LSP doesn't provide syntax highlight, so the feature is still relevant.

**Comment by ValouBambou** [comment]
Since which version ? Because I can't see any sign of this working in my installation of rust-analyzer 1.71.0. Renaming doesn't apply to the variable inside the string format and coloration is still the same as regular string.

**Comment by amaanq** [comment]
> Since which version ? Because I can't see any sign of this working in my installation of rust-analyzer 1.71.0. Renaming doesn't apply to the variable inside the string format and coloration is still the same as regular string.

I can't comment on your IDE/setup, but in Neovim inspecting the LSP semantic tokens shows the following under my cursor

image
image 
image

**Comment by mucinoab** [comment]
I believe that it is okay for tree-sitter to have features that another system already has.

tree-sitter is designed to be very fast and run on every keystroke, rust analyzer on the other hand is not, it has to do a bunch of additional work and, depending the crate/project, this can take seconds or even minutes.

Two systems with two different goals. @amaanq

**Comment by amaanq** [comment]
> I believe that it is okay for tree-sitter to have features that another system already has.

Tree-sitter is not an lsp at all, if so, we'd have knowledge of when an identifier is a type, variable, or function when used anywhere. So that makes no sense

Introducing this would bring false positives in normal strings, rather than false negatives in print-like macro invocations. To me false negatives are better than false positives in this case, anywhere brackets are used would be highlighted incorrectly. You can also solve this with injections by writing a tiny rust format specifier grammar to inject in strings.

**Comment by jfvillablanca** [comment]
> > Since which version ? Because I can't see any sign of this working in my installation of rust-analyzer 1.71.0. Renaming doesn't apply to the variable inside the string format and coloration is still the same as regular string.
> 
> I can't comment on your IDE/setup, but in Neovim inspecting the LSP semantic tokens shows the following under my cursor
> 
> image image image

Hello, I am trying to figure out why I don't get syntax highlighting for string interpolation in rust


I am currently `:Inspect`-ing on `params` in the line `println!("->> {:<12} - handler_hello - {params:?}", "HANDLER");`

I'm wondering if I missed something in my config

**Pull request closed without merging**
