### PR TITLE
Add const generics to type parameters

### LINKED ISSUE #65: Error out when const generics happens
```rust
pub fn uninit_array<const LEN: usize>() -> [Self; LEN] {}
```

This code generate error in the part of const generics.

Error
```
(source_file [0, 0] - [1, 0]
  (function_item [0, 0] - [0, 57]
    (visibility_modifier [0, 0] - [0, 3])
    name: (identifier [0, 7] - [0, 19])
    type_parameters: (type_parameters [0, 19] - [0, 37]
      (constrained_type_parameter [0, 20] - [0, 36]
        left: (type_identifier [0, 20] - [0, 25])
        (ERROR [0, 26] - [0, 29]
          (identifier [0, 26] - [0, 29]))
        bounds: (trait_bounds [0, 29] - [0, 36]
          (primitive_type [0, 31] - [0, 36]))))
    parameters: (parameters [0, 37] - [0, 39])
    return_type: (array_type [0, 43] - [0, 54]
      element: (type_identifier [0, 44] - [0, 48])
      length: (identifier [0, 50] - [0, 53]))
    body: (block [0, 55] - [0, 57])))
```

Expected: not sure in terms of nodes that should happen, but not a error

### PR DESCRIPTION
**Pull request by GrayJack**
This PR is to fix #65 

I have a question before add any tests.

I got this conflict:
```
Unresolved conflict for symbol sequence:

  'impl'  '<'  'const'  •  identifier  …

Possible interpretations:

  1:  'impl'  '<'  (const_generics  'const'  •  identifier  ':'  _type_identifier)
  2:  'impl'  '<'  (function_modifiers_repeat1  'const')  •  identifier  …

Possible resolutions:

  1:  Specify a higher precedence in `const_generics` than in the other rules.
  2:  Specify a higher precedence in `function_modifiers_repeat1` than in the other rules.
  3:  Specify a left or right associativity in `function_modifiers_repeat1`
  4:  Add a conflict for these rules: `function_modifiers`, `const_generics`
```
I decided to do the 4 but not sure is the right decision, but also it's strange that function_modifiers can show inside `type_parameters`

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
Hey @GrayJack, thanks for identifying this problem and opening the PR. It might take me a few work days to get around to reviewing it, but I definitely want to get this fixed.

**Comment by maxbrunsfeld** [comment]
Ok, I looked into this a little bit. I agree that the conflict was surprising.

The problem is actually not that `function_modifiers` can appear inside of `type_parameters` (it can't), it's actually somewhat subtle:

1. The impl item's type name can begin with `<` because of [canonical paths](https://doc.rust-lang.org/reference/paths.html#canonical-paths) and [qualified paths](https://doc.rust-lang.org/reference/paths.html#qualified-paths).

    For example, you could write

    ```rust
    impl <Type1 as Trait1>::Type2 {
        fn some_method_on_type2(&self) {
        }
    }
    ```

2. I think that *Any* type expression can be used in place of `Type1`, even a 'function type' like `FnOnce() -> String`.

3. The problem is that the current grammar allows function modifiers like `const` and `async` at the beginning of trait-based function types (e.g. `const FnOnce() -> String`). In reality, those function modifiers might only be allowed for "bare" function types (written w/ `fn` instead of a trait name).

I think that we *may* be able to fix this by changing `function_type` so that function modifiers like `async` and `const` are *only* allowed with `fn`.

**Comment by maxbrunsfeld** [comment]
After experimenting with `rustc`, I think that this solution ☝️ is fine. It doesn't seem like `unsafe FnOnce` or `async FnMut` are valid.

**Comment by maxbrunsfeld** [comment]
Ok @GrayJack I pushed two small changes: a removal of that conflict, and a rename.

Remaining questions:

1. Are there any other outstanding concerns that you have? I noticed that you left this as a draft.
2. Do we need to change the *call* side of this as well, `type_arguments`, to let you pass const values in as generic arguments?

**Comment by GrayJack** [comment]
Yes, the next step is to allow literals on type_arguments on call site

**Comment by maxbrunsfeld** [comment]
Is it just literals or can you pass arbitrary const expressions (like identifiers, calls to `const fn` functions, etc)?

**Comment by GrayJack** [comment]
As of this time (02/2020), you can pass literals and simple constant identifiers.

```rust
const CONST: u32 = 10;
const CONST2: u32 = 11;

fn foo<const X: u32>() -> u32 {
    X
}

fn main() {
    let _ = foo::<4>(); // Valid
    let _ = foo::<CONST>(); // Valid
    let _ = foo::<(CONST+CONST2)>(); // Invalid
}
```

**Comment by maxbrunsfeld** [comment]
I guess we should probably make it so that any identifier in a `type_argument` list is always parsed as a plain `identifier`, and it would be up to the caller to figure out what is a type and what is a value, similar to how `use` lists are currently parsed.

**Comment by GrayJack** [comment]
I guess we could let as `type_identifier` and let the caller figure out, just to avoid the caller to have to change things

**Comment by maxbrunsfeld** [comment]
This is a great. Thanks @GrayJack.

**Pull request merged**
