### PR TITLE
Fix parse error when a comment was inside a string

### PR DESCRIPTION
**Pull request by calixteman**
When parsing "/* hey */" a comment was seen just after the first ".
So the goal here is to fix that.

### CODE REVIEW

**Comment by calixteman** [comment]
I wonder if it'd be better to add exceptions to extras.
For example:
extras_exception: [$.comment, [$.string, ...]] to say "don't check for comment when in the string state"
I think it'd be a more useful feature than this patch :)
@maxbrunsfeld Wdyt ?

**Comment by calixteman** [comment]
Or another possibility would be to be able to get the current state from the scanner and if state == string_literal then return false when in the block_comment stuff.

**Comment by maxbrunsfeld** [comment]
Yeah, you can do that. You can allow the external scanner to check for the validity of a (non-external) token by adding that token to the `externals` list. So in this case, you could do this:

```js
externals: $ => [
  // existing externals ...
  $.escape_sequence
]
```

Then, in the external scanner you can do this:

```c
enum TokenType {
  // existing external tokens ...

  ESCAPE_SEQUENCE,
};

bool tree_sitter_rust_external_scanner_scan(void *payload, TSLexer *lexer,
const bool *valid_symbols) {

  // other scanner code ...

  // do not parse comments inside of strings
  if (!valid_symbols[ESCAPE_SEQUENCE]) {
    if (lexer->lookahead == '/') {
      // scan comment ...
    }
  }
}
```

**Comment by calixteman** [comment]
@maxbrunsfeld thx it's working well.

**Comment by maxbrunsfeld** [comment]
Thanks!

**Pull request merged**
