### PR TITLE
0.20

### PR DESCRIPTION
**Pull request by Luni-4**
This PR updates `tree-sitter-rust` to 0.20

@maxbrunsfeld 

Can we release it on crates.io also? Thanks in advance! :)

### CODE REVIEW

**Review by aryx — APPROVED** [review]
sure

**Comment by aryx** [comment]
Looks like this was done partially in https://github.com/tree-sitter/tree-sitter-rust/commit/e06d078aaec4f2ba86f170b2102bba6d4646ed4f
@maxbrunsfeld do we need also to update the dependencies to 0.20.0? Or was there a reason
you didn't in the commit above.

**Comment by aryx** [comment]
This might solve https://github.com/tree-sitter/tree-sitter-rust/issues/122?

**Comment by Luni-4** [comment]
@aryx 
Yep, we can close this PR

**Comment by marco-c** [comment]
@Luni-4 Max commit was not updating the tree-sitter dependency, we likely still need to do that.

**Comment by Luni-4** [comment]
I can find `0.20` on crates.io https://crates.io/crates/tree-sitter-rust

**Pull request closed without merging**
